// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrvqnQBDEndcZR-uinpQlMbkkxDJQ7H4',
    appId: '1:787450222363:web:00c753f2ad35d901d0a5be',
    messagingSenderId: '787450222363',
    projectId: 'check-application-cityguide',
    authDomain: 'check-application-cityguide.firebaseapp.com',
    databaseURL: 'https://check-application-cityguide-default-rtdb.firebaseio.com',
    storageBucket: 'check-application-cityguide.appspot.com',
    measurementId: 'G-Y6G5MGNBYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePtB16drlgKKJSU7gv0fcgefCgoikxMw',
    appId: '1:787450222363:android:12aff4a8092df97cd0a5be',
    messagingSenderId: '787450222363',
    projectId: 'check-application-cityguide',
    databaseURL: 'https://check-application-cityguide-default-rtdb.firebaseio.com',
    storageBucket: 'check-application-cityguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdirJujCXtx_-evNU2lYlM2_QTyMSQsZY',
    appId: '1:787450222363:ios:70440a9726196e31d0a5be',
    messagingSenderId: '787450222363',
    projectId: 'check-application-cityguide',
    databaseURL: 'https://check-application-cityguide-default-rtdb.firebaseio.com',
    storageBucket: 'check-application-cityguide.appspot.com',
    androidClientId: '787450222363-qfu54gea57l8lpluqaj8d268hvum45e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginApp',
  );
}
